/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ../public/vmap.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/vmap.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.EXPORT_GOOGLE_SAT_WM.geometry} material={materials.rastMat} />
      <mesh geometry={nodes.Areasbuilding.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[-8961048, 0, 1862020.25]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[93.101, 16.183, -16.217]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.012']} position={[-4.771, 6.074, 57.448]} rotation={[0.025, 0.662, -0.027]} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.003']} position={[93.528, 31.896, -21.271]} rotation={[-Math.PI, 0.01, -Math.PI]} />
      <mesh geometry={nodes.Text001.geometry} material={nodes.Text001.material} position={[15.74, 11.094, 43.092]} rotation={[Math.PI, -0.673, Math.PI]} />
      <mesh geometry={nodes.Text002.geometry} material={nodes.Text002.material} position={[-36.161, 21.038, -60.236]} rotation={[3.031, -0.048, -3.119]} />
      <mesh geometry={nodes.Text003.geometry} material={nodes.Text003.material} position={[-24.583, 21.46, -159.16]} rotation={[-Math.PI, 0.784, -Math.PI]} />
      <mesh geometry={nodes.Text004.geometry} material={nodes.Text004.material} position={[-94.623, 0, 13.051]} />
      <mesh geometry={nodes.Text005.geometry} material={nodes.Text005.material} position={[244.956, 21.448, -214.031]} rotation={[Math.PI, -0.766, Math.PI]} />
      <mesh geometry={nodes.Areasbuilding001.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Text006.geometry} material={nodes.Text006.material} position={[81.916, 82.049, -177.236]} />
      <mesh geometry={nodes.Text007.geometry} material={nodes.Text007.material} position={[115.578, 20.696, -338.063]} rotation={[-3.101, -0.719, -3.099]} />
      <mesh geometry={nodes.Text008.geometry} material={nodes.Text008.material} position={[66.371, 20.835, -317.152]} rotation={[-Math.PI, 0.588, -Math.PI]} />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[130.585, 0, -268.758]} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[86.525, 14.451, -137.945]} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[130.585, 0, -268.758]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.007']} position={[71.142, 27.454, -137.836]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.008']} position={[71.142, 24.145, -137.836]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.009']} position={[71.142, 21.153, -137.836]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.011']} position={[72.169, 24.027, -139.336]} scale={1.803} />
      <mesh geometry={nodes.Text009.geometry} material={nodes.Text009.material} position={[257.016, 20.494, -3.693]} rotation={[Math.PI, -0.077, Math.PI]} />
      <mesh geometry={nodes.Text010.geometry} material={nodes.Text010.material} position={[332.602, 20.599, 227.218]} rotation={[-Math.PI, 0.043, -Math.PI]} />
      <mesh geometry={nodes.Text011.geometry} material={nodes.Text011.material} position={[326.94, 21.429, 50.728]} rotation={[0, -1.515, 0]} />
      <mesh geometry={nodes.Text012.geometry} material={nodes.Text012.material} position={[333.348, 20.599, 118.064]} rotation={[0, -1.515, 0]} />
      <mesh geometry={nodes.Text013.geometry} material={nodes.Text013.material} position={[-189.739, 21.011, 257.952]} rotation={[-Math.PI, 0.842, -Math.PI]} />
      <mesh geometry={nodes.Text014.geometry} material={nodes.Text014.material} position={[-111.075, 25.819, 266.429]} rotation={[-Math.PI, 0.863, -Math.PI]} />
  
    </group>
  )
}

useGLTF.preload('/vmap.glb')
